from bok import Bok
from bokhylle import Bokhylle
from bibliotek import Bibliotek

bok1 = Bok("KiMiNoNaWa",100,2016)
bok2 = Bok("Historie",200,1992)
bok3 = Bok("Filosofi",300,2000)
bok4 = Bok("Hallo",1000,2019)
bok5 = Bok("Hei",100,2011)
bok6 = Bok("Boka",100,193)
bok7 = Bok("Baka",100,2018)
bokhylle1 = Bokhylle(3)
bokhylle2 = Bokhylle(2)
bibliotek1 = Bibliotek()

leggtilBok1 = bokhylle1.leggTilBok(bok1)
assert(leggtilBok1==True)
leggtilBok2 = bokhylle1.leggTilBok(bok2)
assert(leggtilBok2==True)
leggtilBok3 = bokhylle1.leggTilBok(bok3)
assert(leggtilBok3==True)
leggtilBok4 = bokhylle1.leggTilBok(bok4)
assert(leggtilBok4==False)
print()
bokhylle1.hentBoker()
print()
bokhylle1.finnBok("Historie",1992)
bokhylle1.finnBok("Hallo",2019)
print()
bibliotek1.utvidBibliotek(2,3)

bibliotek1.leggTilBibliotek(bok1)
bibliotek1.leggTilBibliotek(bok2)
bibliotek1.leggTilBibliotek(bok3)
bibliotek1.leggTilBibliotek(bok4)
bibliotek1.leggTilBibliotek(bok5)
bibliotek1.leggTilBibliotek(bok6)
bibliotek1.leggTilBibliotek(bok7)
assert(bibliotek1.leggTilBibliotek(bok7) == False)
bibliotek1.finnBoklBibliotek("Baka",2018)
assert(bibliotek1.finnBoklBibliotek("Baka",2018) == False)
print(bibliotek1.finnBoklBibliotek("Boka",193))
bibliotek1.printBok()
bibliotek1.printBokhylle()
